version: '3.3'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: 'db_produtos'
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'password'
    ports:
      - '5432:5432'
    expose:
      - '5432'
    volumes:
      - my-db:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: 'pgadmin@example.com'
      PGADMIN_DEFAULT_PASSWORD: 'pgadminpassword'
    ports:
      - '5050:80'
    depends_on:
      - db

volumes:
  my-db: